development:
  adapter: postgresql
  database: rainforest_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: rainforest_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rainforest_production
  pool: 5
  timeout: 5000
